services:
  postgres:
    image: postgres:16-alpine
    container_name: sample-art-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sample_art}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sample_art}
      POSTGRES_DB: ${POSTGRES_DB:-sample_art}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-sample_art}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes: {}
